### PR TITLE
Password requested on connecting

### PR DESCRIPTION
**Pull request by Duologic**
It is not safe to store passwords clear text, better ask for them when connecting.
Note: This snippet currently does not check wether or not password is already present.

### CODE REVIEW

**Comment by mjbrownie** [comment]
Hi, 

Thanks for the patch. I'm afraid I'm not using and am no longer able to test/maintain this plugin (though I'm always happy to see people using it :)

I'd be inclined to merge/publish a backwards compatible change on vim.org if you believe you have enough energy to write one. Alternately you are more than welcome to publish your own fork (I'd be happy to link to your work).

**Comment by Duologic** [comment]
Next week I'll be in the office again, I'll be trying out the plugin. If it works well, I might write a backwards compatible patch in the near future.

**Comment by Duologic** [comment]
I'm not using Trac anymore, can't test this. You can close and drop this pull request if you want to.

**Comment by mjbrownie** [comment]
Sure Thing.

**Pull request closed without merging**
